### ISSUE TITLE
BUG | Linux版MCSL2打包缺少文件导致无法启动

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [MCSLTeam/MCSL2#137]
### MCSL2 系统报告

# mraodragon @ localhost in ~/.local/share/MCSL2 [18:16:36] 
$ ./MCSL2.bin 1| wl-copy
Traceback (most recent call last):
  File "/home/mraodragon/.local/share/MCSL2/MCSL2.py", line 20, in <module>
  File "/home/mraodragon/.local/share/MCSL2/MCSL2Lib/utils.py", line 34, in <module MCSL2Lib.utils>
  File "/home/mraodragon/.local/share/MCSL2/MCSL2Lib/Controllers/logController.py", line 23, in __init__
  File "/home/mraodragon/.local/share/MCSL2/loguru/_logger.py", line 988, in add
  File "/home/mraodragon/.local/share/MCSL2/loguru/_handler.py", line 93, in __init__
  File "/home/mraodragon/.local/share/MCSL2/multiprocessing/context.py", line 112, in SimpleQueue
  File "/home/mraodragon/.local/share/MCSL2/multiprocessing/queues.py", line 22, in <module>
ImportError: /home/mraodragon/.local/share/MCSL2/_multiprocessing.so: cannot open shared object file: No such file or directory

### 你在哪方面遇到了问题？

启动/关闭MCSL2

### 说明

直接下载，解压

### 附件(可选)

![image](https://github.com/MCSLTeam/MCSL2/assets/67987607/4eb77c1a-a09e-41d3-97a1-cbf52fa54db7)

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by LxHTT** [comment]
Linux版本打包问题，正在debug

**Comment by LxHTT** [comment]
已修复。
