### ISSUE TITLE
BUG | 服务器配置文件不能包含中文？

### ISSUE THREAD

**Issue by LiuJiewenTT** [MCSLTeam/MCSL2#138]
### MCSL2 系统报告

Traceback (most recent call last):
  File "D:\Unzipped Software\mc\MCSL2\MCSL2-~1.1-W\MCSL2Lib\Pages\consolePage.py", line 355, in colorConsoleText
  File "D:\Unzipped Software\mc\MCSL2\MCSL2-~1.1-W\MCSL2Lib\Controllers\serverController.py", line 395, in readServerProperties
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 656: illegal multibyte sequence

### 你在哪方面遇到了问题？

MCSL2启动服务器

### 说明

server.properties不能包含中文吗？我想设置中文的motd

### 附件(可选)

![image](https://github.com/MCSLTeam/MCSL2/assets/43092274/a37ceae3-a3b4-40e2-8f03-5029af0838d9)

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by LxHTT** [comment]
请使用UTF-8格式保存'server.properties'文件。
