### ISSUE TITLE
BUG | 控制台出现错误

### ISSUE THREAD

**Issue by Leonmmcoset** [MCSLTeam/MCSL2#141]
### MCSL2 系统报告

Traceback (most recent call last):
  File "D:\MCSL 2\MCSL2-2.2.3.1-Windows-x64\MCSL2Lib\Pages\consolePage.py", line 355, in colorConsoleText
  File "D:\MCSL 2\MCSL2-2.2.3.1-Windows-x64\MCSL2Lib\Controllers\serverController.py", line 395, in readServerProperties
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa8 in position 812: illegal multibyte sequence

### 你在哪方面遇到了问题？

MCSL2终端

### 说明

我在启动服务器时出现了错误

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by LxHTT** [comment]
This issue is duplicated with https://github.com/MCSLTeam/MCSL2/issues/140  
I'll close this one.
