### ISSUE TITLE
BUG | 2.2.3.1更新→2.2.4.1失败

### ISSUE THREAD

**Issue by kong-que-dnf123** [MCSLTeam/MCSL2#169]
### MCSL2 系统报告

MCSL2系统报告：
生成时间：2024-03-22 19:58:02
Python版本：3.8.10
控件库版本：1.4.0
操作系统：Windows 11 10.0.22631
架构：64bit
内存占用：155.21MB

### 你在哪方面遇到了问题？

MCSL2更新

### 说明

如标题，在更新时失败，且右上角的 `正在下载更新下载结束后将自动重启` 也未自动消失
```
Traceback (most recent call last):
  File "D:\hai_ge_shi\Game\33C33\FU_WU-qi\MCSL2-2.2.3.1-Windows-x86\MCSL2Lib\Controllers\updateController.py", line 82, in renameUpdate
  File "D:\hai_ge_shi\Game\33C33\FU_WU-qi\MCSL2-2.2.3.1-Windows-x86\qfluentwidgets\common\config.py", line 277, in get
AttributeError: 'str' object has no attribute 'value'
```

### 如何复现这个bug？

打开一个2.2.3.1的版本
点击更新
确认更新
稍作等待

### 附件(可选)

![image](https://github.com/MCSLTeam/MCSL2/assets/120994373/feb9823f-bd0d-4f2d-8bba-66701a66132f)

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by XieXiLin2** [comment]
推荐手动下载程序文件进行替换。

**Comment by kong-que-dnf123** [comment]
~翻到一个日志也丢进来吧...~
[MCSL2_2024-03-22_19.log](https://github.com/MCSLTeam/MCSL2/files/14722324/MCSL2_2024-03-22_19.log)
