### ISSUE TITLE
BUG | Forge服务器安装错误

### ISSUE THREAD

**Issue by ccyy512** [MCSLTeam/MCSL2#170]
### MCSL2 系统报告

Traceback (most recent call last):
  File "E:\360MoveData\Users\cy\Desktop\MCSL2-2.2.4.1-Windows-x64\MCSL2Lib\Pages\configurePage.py", line 1926, in postNewServerDispatcher
  File "E:\360MoveData\Users\cy\Desktop\MCSL2-2.2.4.1-Windows-x64\MCSL2Lib\ServerControllers\serverInstaller.py", line 259, in __init__
  File "E:\360MoveData\Users\cy\Desktop\MCSL2-2.2.4.1-Windows-x64\MCSL2Lib\ServerControllers\serverInstaller.py", line 289, in getInstallerData
MCSL2Lib.ServerControllers.serverInstaller.InstallerError: Invalid Forge installer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\360MoveData\Users\cy\Desktop\MCSL2-2.2.4.1-Windows-x64\MCSL2Lib\Pages\configurePage.py", line 1910, in preNewServerDispatcher
  File "E:\360MoveData\Users\cy\Desktop\MCSL2-2.2.4.1-Windows-x64\MCSL2Lib\Pages\configurePage.py", line 2106, in saveNewServer
  File "E:\360MoveData\Users\cy\Desktop\MCSL2-2.2.4.1-Windows-x64\MCSL2Lib\Pages\configurePage.py", line 1967, in postNewServerDispatcher
  File "E:\360MoveData\Users\cy\Desktop\MCSL2-2.2.4.1-Windows-x64\MCSL2Lib\Pages\configurePage.py", line 2162, in afterInstallingForge
AttributeError: 'ConfigurePage' object has no attribute 'installerLogViewer'

### 你在哪方面遇到了问题？

MCSL2新建服务器

### 说明

mc版本是1.7.10，Java是8，forge版本是1614

### 如何复现这个bug？

其他的forge版本我没试过

### 确认

- [x] 我确保我的Issue没有和别人的重复

**Comment by ccyy512** [comment]
也是不错的bug，终于可以休息几天了

**Comment by AresConnor** [comment]
这啥版本的forge

**Comment by AresConnor** [comment]
哦1.7.10啊，1.8以下不做适配，lazy。为什么不直接用thermos （
