### ISSUE TITLE
服务器无法启动

### ISSUE THREAD

**Issue by HoneyBlock** [MCSLTeam/MCSL2#180]
### 你在哪方面遇到了问题？

MCSL2启动服务器

### 说明

无法正常启动服务器

### 如何复现这个bug？

![image](https://github.com/MCSLTeam/MCSL2/assets/98530834/b2b7d874-7e0a-443b-b1c3-4350c7a3fca6)
点击启动后，点击同意无法取消窗口

### 附件(可选)

```python
Traceback (most recent call last):
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\Pages\serverManagerPage.py", line 696, in scrollAreaProcessor
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\Pages\serverManagerPage.py", line 1411, in startServer
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 303, in __init__
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 441, in initSafelyQuitController
AttributeError: 'NoneType' object has no attribute 'serverProcess'
```

### 确认

- [X] 我确认已经熟读了[提问的智慧](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)
- [X] 我确保我的Issue没有和别人的重复

**Comment by ltzXiaoYanMo** [comment]
请重新发送系统报告，你发送的是错误报告

**Comment by HoneyBlock** [comment]
emm，这算是bug吗
我原本已经创建好服务器，并正常使用，然后我进行服务器（开服器中）改名，导致服务器无法启动，然后我刚才把名字改回后，已正常启动，存档并无丢失
![image](https://github.com/MCSLTeam/MCSL2/assets/98530834/a70caeb0-b8b4-4a87-8796-9a239a943c65)

**Comment by ltzXiaoYanMo** [comment]
你要不...发送下MCSL2日志？

**Comment by HoneyBlock** [comment]
额，请问日志在哪可以看到...苦笑.jpg

**Comment by ltzXiaoYanMo** [comment]
呃，你用 `cmd` 打开 MCSL2.exe 也是同样的效果，~~落雪那个若至他没写~~

**Comment by HoneyBlock** [comment]
我这边有好几条log，具体问题出在哪我就不知道了。。。
[MCSL2_2024-05-19_09.log](https://github.com/MCSLTeam/MCSL2/files/15369556/MCSL2_2024-05-19_09.log)
[MCSL2_2024-05-19_20.log](https://github.com/MCSLTeam/MCSL2/files/15369557/MCSL2_2024-05-19_20.log)
[MCSL2_2024-05-19_21.log](https://github.com/MCSLTeam/MCSL2/files/15369558/MCSL2_2024-05-19_21.log)

**Comment by ltzXiaoYanMo** [comment]
这块貌似是 @LxHTT 写的，具体出在哪我就不知道了，代码抽象程度像极了我写史山的样子。。。

这是 MCSL2_2024-04-19_09.log 的 log 文件：
```logs
2024-05-19 09:13:48 | INFO | logController.__init__, at line 55 | 
MCSL2 - 日志
本次启动时间: 2024-05-19 09:13:48
MCSL2 版本: 2.2.5.1 Stable Channel 24309
Python 版本: 3.8.10
Qt 版本: 5.15.2
QFluentWidgets 版本: 1.5.4
操作系统: Windows 11 10.0.22631
CPU: AMD64 Family 25 Model 68 Stepping 1, AuthenticAMD
架构: 64bit
内存占用: 100.24 MB
2024-05-19 09:13:48 | INFO | aria2ClientController.read, at line 848 | 读取下载记录: 0条
2024-05-19 09:13:48 | INFO | aria2ClientController.read, at line 848 | 读取下载记录: 0条
2024-05-19 09:13:50 | INFO | aria2ClientController.run, at line 477 | 启动 Aria2 耗时: 0.1338 秒
2024-05-19 09:13:56 | INFO | processCreator._setJVMArg, at line 230 | 生成 JVM 参数: 
['-Xms2048M', '-Xmx4096M', '-Dlog4j2.formatMsgNoLookups=true', '-jar', 'fabric-server-mc.1.20.4-loader.0.15.11-launcher.1.0.1.jar', 'nogui']
2024-05-19 10:40:15 | ERROR | windowCreator.recordPlayers, at line 1274 | extract player name failed
onRecordPlayers::logout [10:40:15] [服务器线程/信息]: SSJ left the game
Traceback (most recent call last):
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 1270, in recordPlayers
ValueError: 'SSJ' is not in list

2024-05-19 10:40:56 | ERROR | windowCreator.recordPlayers, at line 1274 | extract player name failed
onRecordPlayers::logout [10:40:56] [服务器线程/信息]: SSJ left the game
Traceback (most recent call last):
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 1270, in recordPlayers
ValueError: 'SSJ' is not in list

2024-05-19 10:54:19 | ERROR | windowCreator.recordPlayers, at line 1274 | extract player name failed
onRecordPlayers::logout [10:54:19] [服务器线程/信息]: SSJ left the game
Traceback (most recent call last):
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 1270, in recordPlayers
ValueError: 'SSJ' is not in list
```

MCSL2_2024-04-19_20.log：
```logs
2024-05-19 20:50:36 | INFO | logController.__init__, at line 55 | 
MCSL2 - 日志
本次启动时间: 2024-05-19 20:50:35
MCSL2 版本: 2.2.5.1 Stable Channel 24309
Python 版本: 3.8.10
Qt 版本: 5.15.2
QFluentWidgets 版本: 1.5.4
操作系统: Windows 11 10.0.22631
CPU: AMD64 Family 25 Model 68 Stepping 1, AuthenticAMD
架构: 64bit
内存占用: 100.25 MB
2024-05-19 20:50:36 | INFO | aria2ClientController.read, at line 848 | 读取下载记录: 0条
2024-05-19 20:50:36 | INFO | aria2ClientController.read, at line 848 | 读取下载记录: 0条
2024-05-19 20:50:39 | INFO | aria2ClientController.run, at line 477 | 启动 Aria2 耗时: 0.15192 秒
2024-05-19 20:50:57 | INFO | processCreator._setJVMArg, at line 230 | 生成 JVM 参数: 
['-Xms2048M', '-Xmx4096M', '-Dlog4j2.formatMsgNoLookups=true', '-jar', 'fabric-server-mc.1.20.4-loader.0.15.11-launcher.1.0.1.jar', 'nogui']
2024-05-19 20:58:52 | ERROR | windowInterface.catchExceptions, at line 261 | TypeError: closeEvent() missing 1 required positional argument: 'a0'


2024-05-19 20:58:54 | ERROR | windowInterface.catchExceptions, at line 261 | Traceback (most recent call last):
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\Pages\serverManagerPage.py", line 696, in scrollAreaProcessor
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\Pages\serverManagerPage.py", line 1411, in startServer
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 303, in __init__
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 441, in initSafelyQuitController
AttributeError: 'NoneType' object has no attribute 'serverProcess'


2024-05-19 20:58:56 | ERROR | windowInterface.catchExceptions, at line 261 | Traceback (most recent call last):
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 320, in closeEvent
AttributeError: 'NoneType' object has no attribute 'isServerRunning'


2024-05-19 20:59:48 | ERROR | windowInterface.catchExceptions, at line 261 | TypeError: closeEvent() missing 1 required positional argument: 'a0'


2024-05-19 20:59:49 | ERROR | windowInterface.catchExceptions, at line 261 | Traceback (most recent call last):
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\Pages\serverManagerPage.py", line 696, in scrollAreaProcessor
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\Pages\serverManagerPage.py", line 1411, in startServer
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 303, in __init__
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 441, in initSafelyQuitController
AttributeError: 'NoneType' object has no attribute 'serverProcess'


2024-05-19 20:59:51 | ERROR | windowInterface.catchExceptions, at line 261 | Traceback (most recent call last):
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 320, in closeEvent
AttributeError: 'NoneType' object has no attribute 'isServerRunning'


2024-05-19 21:00:23 | ERROR | windowInterface.catchExceptions, at line 261 | TypeError: closeEvent() missing 1 required positional argument: 'a0'


2024-05-19 21:00:24 | ERROR | windowInterface.catchExceptions, at line 261 | Traceback (most recent call last):
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\Pages\serverManagerPage.py", line 696, in scrollAreaProcessor
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\Pages\serverManagerPage.py", line 1411, in startServer
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 303, in __init__
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 441, in initSafelyQuitController
AttributeError: 'NoneType' object has no attribute 'serverProcess'


2024-05-19 21:00:26 | ERROR | windowInterface.catchExceptions, at line 261 | Traceback (most recent call last):
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 320, in closeEvent
AttributeError: 'NoneType' object has no attribute 'isServerRunning'
```

MCSL2_2024-04-19_21.log：
```
2024-05-19 21:00:41 | INFO | logController.__init__, at line 55 | 
MCSL2 - 日志
本次启动时间: 2024-05-19 21:00:40
MCSL2 版本: 2.2.5.1 Stable Channel 24309
Python 版本: 3.8.10
Qt 版本: 5.15.2
QFluentWidgets 版本: 1.5.4
操作系统: Windows 11 10.0.22631
CPU: AMD64 Family 25 Model 68 Stepping 1, AuthenticAMD
架构: 64bit
内存占用: 100.3 MB
2024-05-19 21:00:41 | INFO | aria2ClientController.read, at line 848 | 读取下载记录: 0条
2024-05-19 21:00:41 | INFO | aria2ClientController.read, at line 848 | 读取下载记录: 0条
2024-05-19 21:00:46 | INFO | aria2ClientController.run, at line 477 | 启动 Aria2 耗时: 3.36635 秒
2024-05-19 21:00:59 | ERROR | windowInterface.catchExceptions, at line 261 | TypeError: closeEvent() missing 1 required positional argument: 'a0'


2024-05-19 21:01:07 | ERROR | windowInterface.catchExceptions, at line 261 | Traceback (most recent call last):
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\Pages\serverManagerPage.py", line 696, in scrollAreaProcessor
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\Pages\serverManagerPage.py", line 1411, in startServer
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 303, in __init__
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 441, in initSafelyQuitController
AttributeError: 'NoneType' object has no attribute 'serverProcess'


2024-05-19 21:02:48 | ERROR | windowInterface.catchExceptions, at line 261 | Traceback (most recent call last):
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 320, in closeEvent
AttributeError: 'NoneType' object has no attribute 'isServerRunning'


2024-05-19 21:05:26 | ERROR | windowInterface.catchExceptions, at line 261 | TypeError: closeEvent() missing 1 required positional argument: 'a0'


2024-05-19 21:05:28 | ERROR | windowInterface.catchExceptions, at line 261 | Traceback (most recent call last):
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\Pages\serverManagerPage.py", line 696, in scrollAreaProcessor
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\Pages\serverManagerPage.py", line 1411, in startServer
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 303, in __init__
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 441, in initSafelyQuitController
AttributeError: 'NoneType' object has no attribute 'serverProcess'


2024-05-19 21:05:40 | ERROR | windowInterface.catchExceptions, at line 261 | Traceback (most recent call last):
  File "E:\software\MCSL2-2.2.5.1-Windows-x64\MCSL2Lib\ServerControllers\windowCreator.py", line 320, in closeEvent
AttributeError: 'NoneType' object has no attribute 'isServerRunning'


2024-05-19 21:08:50 | INFO | aria2ClientController.pauseDownloadTask, at line 325 | Aria2 下载已暂停: 3bc44739feeb4cf6
2024-05-19 21:08:52 | INFO | aria2ClientController.cancelDownloadTask, at line 346 | Aria2 下载已取消: 3bc44739feeb4cf6
2024-05-19 21:08:52 | INFO | aria2ClientController.updateDownloadInfo, at line 569 | 下载被取消
2024-05-19 21:08:54 | INFO | windowInterface.catchExceptions, at line 252 | 忽略了异常: <class 'RuntimeError'> wrapped C/C++ object of type NavigationTreeWidget has been deleted <traceback object at 0x0000013E0CE44E40>
2024-05-19 21:08:54 | INFO | windowInterface.catchExceptions, at line 252 | 忽略了异常: <class 'RuntimeError'> wrapped C/C++ object of type NavigationTreeWidget has been deleted <traceback object at 0x0000013E0CE44280>
2024-05-19 21:08:54 | INFO | windowInterface.catchExceptions, at line 252 | 忽略了异常: <class 'RuntimeError'> wrapped C/C++ object of type NavigationTreeWidget has been deleted <traceback object at 0x0000013E22E54800>
2024-05-19 21:08:54 | INFO | windowInterface.catchExceptions, at line 252 | 忽略了异常: <class 'RuntimeError'> wrapped C/C++ object of type NavigationTreeWidget has been deleted <traceback object at 0x0000013E0CE67600>
2024-05-19 21:08:54 | INFO | windowInterface.catchExceptions, at line 252 | 忽略了异常: <class 'RuntimeError'> wrapped C/C++ object of type NavigationTreeWidget has been deleted <traceback object at 0x0000013E0CE44E40>
2024-05-19 21:08:54 | INFO | windowInterface.catchExceptions, at line 252 | 忽略了异常: <class 'RuntimeError'> wrapped C/C++ object of type NavigationTreeWidget has been deleted <traceback object at 0x0000013E0CE44280>
2024-05-19 21:08:54 | INFO | windowInterface.catchExceptions, at line 252 | 忽略了异常: <class 'RuntimeError'> wrapped C/C++ object of type NavigationTreeWidget has been deleted <traceback object at 0x0000013E22E54800>
2024-05-19 21:08:54 | INFO | windowInterface.catchExceptions, at line 252 | 忽略了异常: <class 'RuntimeError'> wrapped C/C++ object of type NavigationTreeWidget has been deleted <traceback object at 0x0000013E0CE67600>
2024-05-19 21:08:56 | INFO | windowInterface.catchExceptions, at line 252 | 忽略了异常: <class 'RuntimeError'> wrapped C/C++ object of type NavigationTreeWidget has been deleted <traceback object at 0x0000013E0CE44E40>
2024-05-19 21:08:56 | INFO | windowInterface.catchExceptions, at line 252 | 忽略了异常: <class 'RuntimeError'> wrapped C/C++ object of type NavigationTreeWidget has been deleted <traceback object at 0x0000013E0CE44280>
2024-05-19 21:08:56 | INFO | windowInterface.catchExceptions, at line 252 | 忽略了异常: <class 'RuntimeError'> wrapped C/C++ object of type NavigationTreeWidget has been deleted <traceback object at 0x0000013E22E54800>
2024-05-19 21:08:56 | INFO | windowInterface.catchExceptions, at line 252 | 忽略了异常: <class 'RuntimeError'> wrapped C/C++ object of type NavigationTreeWidget has been deleted <traceback object at 0x0000013E0CE67600>
2024-05-19 21:08:56 | INFO | windowInterface.catchExceptions, at line 252 | 忽略了异常: <class 'RuntimeError'> wrapped C/C++ object of type NavigationTreeWidget has been deleted <traceback object at 0x0000013E0CE44E40>
2024-05-19 21:08:56 | INFO | windowInterface.catchExceptions, at line 252 | 忽略了异常: <class 'RuntimeError'> wrapped C/C++ object of type NavigationTreeWidget has been deleted <traceback object at 0x0000013E0CE44280>
2024-05-19 21:08:56 | INFO | windowInterface.catchExceptions, at line 252 | 忽略了异常: <class 'RuntimeError'> wrapped C/C++ object of type NavigationTreeWidget has been deleted <traceback object at 0x0000013E22E54800>
2024-05-19 21:08:56 | INFO | windowInterface.catchExceptions, at line 252 | 忽略了异常: <class 'RuntimeError'> wrapped C/C++ object of type NavigationTreeWidget has been deleted <traceback object at 0x0000013E0CE67600>
2024-05-19 21:08:59 | INFO | windowInterface.catchExceptions, at line 252 | 忽略了异常: <class 'RuntimeError'> wrapped C/C++ object of type QPropertyAnimation has been deleted <traceback object at 0x0000013E22E54800>
2024-05-19 21:09:31 | INFO | processCreator._setJVMArg, at line 230 | 生成 JVM 参数: 
['-Xms2048M', '-Xmx4096M', '-Dlog4j2.formatMsgNoLookups=true', '-jar', 'fabric-server-mc.1.20.4-loader.0.15.11-launcher.1.0.1.jar', 'nogui']
2024-05-19 21:15:03 | INFO | logController.__init__, at line 55 | 
MCSL2 - 日志
本次启动时间: 2024-05-19 21:15:02
MCSL2 版本: 2.2.5.1 Stable Channel 24309
Python 版本: 3.8.10
Qt 版本: 5.15.2
QFluentWidgets 版本: 1.5.4
操作系统: Windows 11 10.0.22631
CPU: AMD64 Family 25 Model 68 Stepping 1, AuthenticAMD
架构: 64bit
内存占用: 100.29 MB
2024-05-19 21:15:03 | INFO | aria2ClientController.read, at line 848 | 读取下载记录: 0条
2024-05-19 21:15:03 | INFO | aria2ClientController.read, at line 848 | 读取下载记录: 0条
2024-05-19 21:15:05 | INFO | aria2ClientController.run, at line 477 | 启动 Aria2 耗时: 0.13646 秒
2024-05-19 21:15:08 | INFO | windowInterface.catchExceptions, at line 252 | 忽略了异常: <class 'RuntimeError'> wrapped C/C++ object of type QPropertyAnimation has been deleted <traceback object at 0x000001BA2AA8D800>
```

**Comment by HoneyBlock** [comment]
感觉问题在启动器改名时 sever文件夹里面的服务器名字没有改变，然后索引不到了（我猜的）

**Comment by LxHTT** [comment]
fixed
