### ISSUE TITLE
archlinux下无法启动

### ISSUE THREAD

**Issue by plokid** [MCSLTeam/MCSL2#98]
### MCSL2 系统报告

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ploki/Program/MCSL2/MCSL2Lib/windowInterface.py", line 303, in catchExceptions
    box = MessageBox("程序出现异常", tracebackString, parent=self)
  File "/home/ploki/.pyenv/versions/3.8.17/lib/python3.8/site-packages/qfluentwidgets/components/dialog_box/dialog.py", line 133, in __init__
    super().__init__(parent=parent)
  File "/home/ploki/.pyenv/versions/3.8.17/lib/python3.8/site-packages/qfluentwidgets/components/dialog_box/mask_dialog_base.py", line 15, in __init__
    self._hBoxLayout = QHBoxLayout(self)
SystemError: <class 'PyQt5.QtWidgets.QHBoxLayout'> returned a result with an error set

Original exception was:
Traceback (most recent call last):
  File "/home/ploki/Program/MCSL2/MCSL2Lib/windowInterface.py", line 579, in eventFilter
    if a0 == self.consoleInterface and a1.type() == QEvent.KeyPress:
AttributeError: 'Window' object has no attribute 'consoleInterface'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/ploki/Program/MCSL2/MCSL2Lib/windowInterface.py", line 579, in eventFilter
    if a0 == self.consoleInterface and a1.type() == QEvent.KeyPress:
AttributeError: 'Window' object has no attribute 'consoleInterface'

### 你在哪方面遇到了问题？

启动/关闭MCSL2

### 说明

系统：Arch Linux x86_64 6.4.10-zen2-1-zen
架构：x86_64
MCSL 2 版本：2.2.0.1

上面的报错会一直循环
在MCSL2Lib/windowInterface.py，在174行给self.consoleInterface赋值之前就出现错误并调用eventFilter，导致循环报错

### 确认

- [X] 我确保我的Issue没有和别人的重复

**Comment by AresConnor** [comment]
请检查https://github.com/MCSLTeam/MCSL2/commit/b3fc6da767a174aa827279f1d6ff3d8f29485393，通过设置init变量，在主窗口未初始化前禁用自定义的事件过滤器，应该能解决问题，如果不能的话，请继续提出

**Comment by plokid** [comment]
还是有问题，在eventFilter函数的头两行陷入循环调用
